src/main/java/lt/vtvpmc/exam/entities/Client.java
package lt.vtvpmc.exam.entities;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;


@Entity
public class Client implements Serializable {
    
	private static final long serialVersionUID = -4082230778255953111L;

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column
    private Long id;
    
	@Column (name = "first_name")
    private String firstName;
    
	@Column (name = "last_name")
    private String lastName;
    
	@Column (name = "phone_number")
	private String phoneNumber;
	
	@Column (name = "city")
    private String city;
    
    @OneToMany(mappedBy = "client", orphanRemoval = true, fetch = FetchType.EAGER)
    private List<Survey> surveys;

    public Client() {
    }

    public Client(String firstName, String lastName, String phoneNumber, String city) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.city = city;
    }
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public List<Survey> getSurveys() {
		return surveys;
	}

	public void setSurveys(List<Survey> surveys) {
		this.surveys = surveys;
	} 
	
	 @Override
	    public String toString() {
	        return ("client id: " + id + " name: " + firstName + " " + lastName
	        		+ " answered " + surveys.size() + " surveys");
	    }
}

src/main/java/lt/vtvpmc/exam/entities/Survey.java
package lt.vtvpmc.exam.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Survey implements Serializable {
	
	private static final long serialVersionUID = 5583853763074630122L;
	
	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column
    private Long id;
	
	@Column (name = "question")
	private String question;
	
	@Column (name = "client_evaluation")
	private int value;
	
	@Column (name = "survey_date")
	@Temporal(TemporalType.DATE)
    private Date surveyDate;
	
	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "client_id")
    private Client client;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getValue() {
		return value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	public Date getSurveyDate() {
		return surveyDate;
	}

	public void setSurveyDate(Date surveyDate) {
		this.surveyDate = surveyDate;
	}
	
	public String getQuestion() {
		return question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Survey(){
	}

	public Survey(Client client, Date surveyDate, String question, int value) {
		this.client = client;
		this.surveyDate = surveyDate;
		this.question = question;
		this.value = value;
	}
	
	@Override
    public String toString() {
        return ("survey id: " + id + " answered by: " + client.getFirstName() + " " + client.getLastName()
        		+ " evaluation is " + value);
    }

}

src/main/java/lt/vtvpmc/exam/ui/ClientListBean.java
package lt.vtvpmc.exam.ui;

import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import lt.vtvpmc.exam.entities.Client;

import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.BarChartModel;
import org.primefaces.model.chart.ChartSeries;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.transaction.annotation.Transactional;


public class ClientListBean {
	
	static final Logger logger = LoggerFactory.getLogger(ClientListBean.class);
    
    @PersistenceContext
    private EntityManager entityManager;
    
    private BarChartModel barModel;
    
    @Transactional(readOnly = true)
    public List<Client> getClientList() {
        Query q = entityManager.createQuery("select c from Client c");
        logger.info("All client list returned");
        return q.getResultList();
    }
    
    @Transactional
    public String removeClient(Client client) {
        entityManager.remove(entityManager.merge(client));
        logger.info("Client removed");
        return "main";
    }
    
    @Transactional
    public List<Client> getCriticsList(){
    	Query q = entityManager.createQuery ("select client from Survey s where s.surveyDate =(select max(surveyDate) from Survey s2 where s2.id=s.id) and s.value <=6");
    	logger.info("Critics list returend");
    	return q.getResultList();
    }
    
    @Transactional
    public List<Client> getNeutralList(){
    	Query q = entityManager.createQuery ("select client from Survey s where s.surveyDate =(select max(surveyDate) from Survey s2 where s2.id=s.id) and s.value between 7 and 8");
    	logger.info("Neutrals list returend");
    	return q.getResultList();
    }
    
    @Transactional
    public List<Client> getPromotersList(){
    	Query q = entityManager.createQuery ("select client from Survey s where s.surveyDate =(select max(surveyDate) from Survey s2 where s2.id=s.id) and s.value between 9 and 10");
    	logger.info("Promoters list returend");
    	return q.getResultList();
    }
    
    public void updateGrowl() {
        Long clientCount = Long.valueOf(getClientList().size());
        if (clientCount < 2) {
            FacesMessage warningMessage = new FacesMessage("At least 2 customers are required");
            FacesContext.getCurrentInstance().addMessage(null, warningMessage);
        }
    }

	public BarChartModel getBarModel() {
		createChartBar();
		return barModel;
	}
	
	private void createChartBar() {
        createBarModel();
        logger.info("Bar chart model created");
	}

	 private BarChartModel initBarModel() {
	        BarChartModel model = new BarChartModel();
	 
	        ChartSeries critics = new ChartSeries();
	        critics.setLabel("Critics");
	        critics.set("critics", getCriticsList().size());
	       
	 
	        ChartSeries neutrals = new ChartSeries();
	        neutrals.setLabel("Neutrals");
	        neutrals.set("neutrals", getNeutralList().size());
	        
	        ChartSeries promoters = new ChartSeries();
	        promoters.setLabel("Promoters");
	        promoters.set("promoters", getPromotersList().size());
	        
	 
	        model.addSeries(critics);
	        model.addSeries(neutrals);
	        model.addSeries(promoters);
	         
	        return model;
	    }
	 
	 private void createBarModel() {
	        barModel = initBarModel();
	         
	        barModel.setTitle("Customers type chart");
	        barModel.setLegendPosition("ne");
	         
	        Axis xAxis = barModel.getAxis(AxisType.X);
	        xAxis.setLabel("Type");
	         
	        Axis yAxis = barModel.getAxis(AxisType.Y);
	        yAxis.setLabel("Number of answers");
	        yAxis.setMin(0);
	        yAxis.setMax(20);
	    }
	     
    
}

src/main/java/lt/vtvpmc/exam/ui/NewClientBean.java
package lt.vtvpmc.exam.ui;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import lt.vtvpmc.exam.entities.Client;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.transaction.annotation.Transactional;



public class NewClientBean {
	
	static final Logger logger = LoggerFactory.getLogger(NewClientBean.class);
    
    @PersistenceContext
    private EntityManager entityManager;
    
    private String clientFirstName;
    private String clientLastName;
    private String clientPhoneNumber;
    private String city;
    private Client client;
    
    @Transactional
    public String save() {
        Client client = new Client(clientFirstName, clientLastName, clientPhoneNumber, city);
        entityManager.persist(client);
        logger.info("New customer saved");
        return "main";
    }
    
    public String open(Client client) {
        setClient(client);
        return "addSurvey";
    }
    
    public String getClientFirstName() {
        return clientFirstName;
    }

    public void setClientFirstName(String clientFirstName) {
        this.clientFirstName = clientFirstName;
    }

    public String getClientLastName() {
        return clientLastName;
    }

    public void setClientLastName(String clientLastName) {
        this.clientLastName = clientLastName;
    }

    public String getClientPhoneNumber() {
        return clientPhoneNumber;
    }

    public void setClientPhoneNumber(String clientPhoneNumber) {
        this.clientPhoneNumber = clientPhoneNumber;
    }

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}
    

    
}

src/main/java/lt/vtvpmc/exam/ui/NewSurveyBean.java
package lt.vtvpmc.exam.ui;

import java.util.Date;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.transaction.annotation.Transactional;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.Survey;

public class NewSurveyBean {
	
	static final Logger logger = LoggerFactory.getLogger(NewSurveyBean.class);
	
	@PersistenceContext
    private EntityManager entityManager;
	
	private Client client;
	private Date surveyDate;
	private String question;
	private int value;
	
	@Transactional
    public String saveSurvey(Client client) {
		client = findClientById(client.getId());
		this.client = client;
        Survey survey = new Survey(client, surveyDate, question, value);
        entityManager.persist(survey);
        client.getSurveys().add(survey);
        entityManager.persist(client);
        logger.info("New survey created for the client");
        return "addSurvey";
    }

	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Date getSurveyDate() {
		return surveyDate;
	}

	public void setSurveyDate(Date surveyDate) {
		this.surveyDate = surveyDate;
	}

	public int getValue() {
		return value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	public String getQuestion() {
		return question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}
	
	private Client findClientById(Long id) {
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Client> cq = cb.createQuery(Client.class);
			Root<Client> root = cq.from(Client.class);
			cq.where(cb.equal(root.get("id"), id));
			TypedQuery<Client> q = entityManager.createQuery(cq);
			return q.getSingleResult();
		} finally {
			entityManager.close();
		}
	}
	
}

src/main/java/lt/vtvpmc/exam/ui/SurveyListBean.java
package lt.vtvpmc.exam.ui;

import java.util.Date;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.persistence.criteria.Subquery;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.transaction.annotation.Transactional;

import lt.vtvpmc.exam.entities.Client;
import lt.vtvpmc.exam.entities.Survey;

public class SurveyListBean {
	
	static final Logger logger = LoggerFactory.getLogger(SurveyListBean.class);
	
	@PersistenceContext
    private EntityManager entityManager;
	
	@Transactional
    public void removeSurvey(Survey survey) {
		Client client = survey.getClient();
		client.getSurveys().remove(survey);
		entityManager.persist(findClientById(client.getId()));
        entityManager.remove(entityManager.merge(survey));
        logger.info("Survey removed");
    }
	
	@Transactional(readOnly = true)
    public List<Survey> getAllSurvey() {
        Query q = entityManager.createQuery("select s from Survey s");
        logger.info("All surveys returned");
        return q.getResultList();
    }
	
	@Transactional
	public List<Survey> findAllSurveysByClient(Client client) {
        try {
            CriteriaBuilder cb = entityManager.getCriteriaBuilder();
            CriteriaQuery<Survey> cq = cb.createQuery(Survey.class);
            Root<Survey> root = cq.from(Survey.class);
            cq.select(root);
            cq.where(cb.equal(root.get("client"), client));
            TypedQuery<Survey> q = entityManager.createQuery(cq);
            logger.info("Client's survey returend");
            return q.getResultList();
        } finally {
            entityManager.close();
        }
	}
	
	@Transactional(readOnly = true)
    public List<Survey> getSurveyByClient(Client client) {
        Query q = entityManager.createQuery("select s from Survey s where s.client=:client");
        q.setParameter("client", client);
        logger.info("Client's survey returend");
        return q.getResultList();
    }
	
	@Transactional
	public Double findAverageAnswer() {
		Query q = entityManager.createQuery("select avg(value) from Survey s where s.surveyDate =(select max(surveyDate) from Survey s2 where s2.id=s.id)");
		logger.info("Average of all latest answers counted");
		return (Double) q.getSingleResult();
	}
	
	public void updateGrowl() {
        Long surveyCount = Long.valueOf(getAllSurvey().size());
        if (surveyCount == null || surveyCount == 0) {
            FacesMessage warningMessage = new FacesMessage("There are no surveys done for this customer yet");
            FacesContext.getCurrentInstance().addMessage(null, warningMessage);
        }
    }
	
	private Client findClientById(Long id) {
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Client> cq = cb.createQuery(Client.class);
			Root<Client> root = cq.from(Client.class);
			cq.where(cb.equal(root.get("id"), id));
			TypedQuery<Client> q = entityManager.createQuery(cq);
			return q.getSingleResult();
		} finally {
			entityManager.close();
		}
	}
	

}

src/main/webapp/addNewCustomer.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Call Center</title>
    </h:head>
    
    <h:body>
        <h:form id="newCustomerForm">
            <h3>Add New Client</h3>
            <h:panelGrid columns="3">
                <h:outputText value="Name:"/>
                <h:inputText id="clientName" value="#{newClientBean.clientFirstName}" required="true"/>
                <h:message for="clientName"/>
                
                <h:outputText value="Surname:"/>
                <h:inputText id="clientSurname" value="#{newClientBean.clientLastName}" required="true"/>
                <h:message for="clientSurname"/>
                
                <h:outputText value="Phone #:"/>
                <h:inputText id="clientPhoneNo" value="#{newClientBean.clientPhoneNumber}" required="true"/>
                <h:message for="clientPhoneNo"/>
                
                <h:outputText value="City:"/>
                <h:inputText id="clientCity" value="#{newClientBean.city}" required="true"/>
                <h:message for="clientCity"/>
                
            </h:panelGrid>
            <h:commandButton action="#{newClientBean.save()}" value="Add"/>
        </h:form>
    </h:body>
</html>

src/main/webapp/addSurvey.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<ui:define name="title">
        Surveys
    </ui:define>

	<ui:define name="content">
	<br/>
		<h:form id="clientInfo">
			<p:panelGrid columns="2">
				<f:facet name="header">Customer Info</f:facet>
				<h:outputText value="First Name" />
				<h:outputText value="#{newClientBean.client.firstName}" />

				<h:outputText value="Last Name" />
				<h:outputText value="#{newClientBean.client.lastName}" />

				<h:outputText value="City" />
				<h:outputText value="#{newClientBean.client.city}" />

				<h:outputText value="Phone number" />
				<h:outputText value="#{newClientBean.client.phoneNumber}" />
			</p:panelGrid>
		</h:form>

		<br />

		<h:form id="newSurveyForm">
			<h3>Add New Survey</h3>
			<h:panelGrid columns="3">
				<p:outputLabel for="surveyDate">Date:</p:outputLabel>
				<p:calendar id="surveyDate" value="#{newSurveyBean.surveyDate}">
				</p:calendar>
				<p:message for="surveyDate"></p:message>

				<p:outputLabel for="question">Question:</p:outputLabel>
				<p:inputText id="question" value="#{newSurveyBean.question}"
					required="true" />
				<h:message for="question" />

				<p:outputLabel for="answer">Answer:</p:outputLabel>
				<p:inputText id="answer" value="#{newSurveyBean.value}"
					required="true" />
				<h:message for="answer" />

			</h:panelGrid>
			<h:commandLink
				actionListener="#{newSurveyBean.saveSurvey(newClientBean.client)}"
				value="Save survey" />
		</h:form>

		<br />

		<h:form id="surveyTable">
			<p:growl id="growl" sticky="true" />
			<p:remoteCommand name="onload"
				action="#{surveyListBean.updateGrowl()}" autoRun="true"
				update="growl" />
			<p:dataTable value="#{surveyListBean.findAllSurveysByClient(newClientBean.client)}" var="survey">
				<f:facet name="header">Survey Details</f:facet>
				<p:column headerText="Survey date">
					<h:outputText value="#{survey.surveyDate}" />
				</p:column>

				<p:column headerText="Customer phone:">
					<h:outputText value="#{survey.client.phoneNumber}" />
				</p:column>

				<p:column headerText="Question">
					<h:outputText value="#{survey.question}" />
				</p:column>
				<p:column headerText="Answer (value)">
					<h:outputText value="#{survey.value}" />
				</p:column>
				<p:column headerText="">
					<h:commandLink
						actionListener="#{surveyListBean.removeSurvey(survey)}"
						value="Delete" />
				</p:column>
			</p:dataTable>
		</h:form>
	</ui:define>
	<br/>

	<ui:define name="footer">
		<ui:include src="footer.xhtml" />
	</ui:define>
</ui:composition>

src/main/webapp/dataView.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<ui:define name="title">
        All data
    </ui:define>
    
    <ui:define name="content">
    <br/>
		<h:form id="dataTable">
			<p:growl id="growl" sticky="true" />
			<p:remoteCommand name="onload"
				action="#{surveyListBean.updateGrowl()}" autoRun="true"
				update="growl" />
			<p:dataTable value="#{surveyListBean.getAllSurvey()}" var="survey">
				<f:facet name="header">All surveys data:</f:facet>
				<p:column headerText="Survey ID">
					<h:outputText value="#{survey.id}" />
				</p:column>
				
				<p:column headerText="Survey date">
					<h:outputText value="#{survey.surveyDate}" />
				</p:column>

				<p:column headerText="Customer phone:">
					<h:outputText value="#{survey.client.phoneNumber}" />
				</p:column>
				
				<p:column headerText="Customer first name:">
					<h:outputText value="#{survey.client.firstName}" />
				</p:column>
				
				<p:column headerText="Customer last name:">
					<h:outputText value="#{survey.client.lastName}" />
				</p:column>

				<p:column headerText="Question">
					<h:outputText value="#{survey.question}" />
				</p:column>
				<p:column headerText="Answer (value)">
					<h:outputText value="#{survey.value}" />
				</p:column>
			</p:dataTable>
		</h:form>
		<br/>
		<h:form id="average">
			<p:panelGrid columns="2">
				<f:facet name="header">Average value of answers:</f:facet>
				<h:outputText value="How do you like our service?" />
				<h:outputText value="#{surveyListBean.findAverageAnswer()}" />
			</p:panelGrid>
		</h:form>
		
		<br/>
		<h:form id="barChart">
		<p:chart type="bar" model="#{clientListBean.barModel}" style="height:300px"/>
		</h:form>
		
	</ui:define>
	<br/>
	
	<ui:define name="footer">
		<ui:include src="footer.xhtml" />
	</ui:define>
</ui:composition>

src/main/webapp/footer.xhtml
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head></h:head>
<h:body>
    <ui:composition>
        <div id="tele_footer">
        <img src="/exam/resources/tele_footer.jpg"/>
        </div>
    </ui:composition>
</h:body>
</h:html>

src/main/webapp/layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <title>Customers: 
        <ui:insert name="title">
            No title
        </ui:insert>
    </title>
    <h:outputStylesheet name="style.css"></h:outputStylesheet>
</h:head>
<h:body>
    <div id="container">
        <div id="menu">
            <h:form>
                <p:tabMenu>
                    <p:menuitem value="Customers" outcome="main" icon="ui-icon-scissors">
                    </p:menuitem>
                    <p:menuitem value="Survey Data" outcome="dataView" icon="ui-icon-scissors">
                    </p:menuitem>
                </p:tabMenu>
            </h:form>
        </div>
        <div id="layout">
            <div id="leftside">
                <ui:insert name="leftside" />
            </div>
            <div id="rightside">
                <ui:insert name="rightside" />
            </div>
        </div>
        <div id="contents">
            <ui:insert name="content" />
        </div>
    </div>
    <div id="footer-container">
        <ui:insert name="footer" />
    </div>
</h:body>
</html>

src/main/webapp/main.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

	<h:head>
		<title>Call Center</title>
		<h:outputStylesheet name="styles.css" />
	</h:head>

	<ui:define name="content">
	<br/>
		<h:form id="dataTable">
			<p:growl id="growl" sticky="true" />
			<p:remoteCommand name="onload"
				action="#{clientListBean.updateGrowl()}" autoRun="true"
				update="growl" />
			<p:dataTable value="#{clientListBean.clientList}" var="client">
				<f:facet name="header">Registered Customers</f:facet>
				<p:column headerText="First name">
					<h:outputText value="#{client.firstName}" />
				</p:column>
				<p:column headerText="Last Name">
					<h:outputText value="#{client.lastName}" />
				</p:column>
				<p:column headerText="City">
					<h:outputText value="#{client.city}" />
				</p:column>

				<p:column headerText="">
					<p:commandButton value="Add Survey"
						action="#{newClientBean.open(client)}">
					</p:commandButton>
				</p:column>
				<p:column headerText="">
					<h:commandLink actionListener="#{clientListBean.removeClient(client)}" value="Delete"/>
				</p:column>
			</p:dataTable>
		</h:form>
		<br/>

		<h:form id="actionForm">
			<h:commandButton id="addNewCustomerBtn" action="addNewCustomer"
				value="Add New Customer" />
		</h:form>
		
		<br/>
		<h:form id="dataForm">
			<h:commandButton id="datViewBtn" action="dataView"
				value="All surveys data" />
		</h:form>


	</ui:define>

	<ui:define name="footer">
		<ui:include src="footer.xhtml" />
	</ui:define>

</ui:composition>